//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.08 at 11:50:34 AM EEST 
//


package oasis.names.specification.ubl.schema.xsd.tendercontract_2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the oasis.names.specification.ubl.schema.xsd.tendercontract_2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TenderContract_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:TenderContract-2", "TenderContract");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: oasis.names.specification.ubl.schema.xsd.tendercontract_2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TenderContractType }
     * 
     */
    public TenderContractType createTenderContractType() {
        return new TenderContractType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TenderContractType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:TenderContract-2", name = "TenderContract")
    public JAXBElement<TenderContractType> createTenderContract(TenderContractType value) {
        return new JAXBElement<TenderContractType>(_TenderContract_QNAME, TenderContractType.class, null, value);
    }

}
